### PR TITLE
add acala and karura bootnodes for smoldot

### PR DESCRIPTION
**Pull request by Ank4n**

### CODE REVIEW

**Review by tomaka — APPROVED** [review]

**Comment by tomaka** [comment]
I just want to point out that these chain specs are not published in any way whatsoever and exist just for me locally to test whether smoldot manages to connect to Acala/Karura.

**Comment by Ank4n** [comment]
> I just want to point out that these chain specs are not published in any way whatsoever and exist just for me (or any dev working on this repo) locally to test whether smoldot manages to connect to Acala/Karura.

Thanks for letting me know. Where are the known chain specs for substrate connect are stored?

**Comment by tomaka** [comment]
substrate-connect doesn't provide chain specs. Users of substrate-connect pass the chain spec as parameter.

**Comment by Ank4n** [comment]
Ok good to know. Please merge it still. Thanks. 🙏

**Pull request merged**
