### PR TITLE
Add a grandpa warp sync service to the wasm node

### PR DESCRIPTION
**Pull request by expenses**
We can finally tie everything together now! 🚀

### CODE REVIEW

**Comment by tomaka** [comment]
Well, we're not supposed to have a separate GrandPa warp sync service. It should be handled by the sync service. :grimacing:

**Comment by expenses** [comment]
> Well, we're not supposed to have a separate GrandPa warp sync service. It should be handled by the sync service.

How would you like me to integrate it with that?

**Comment by tomaka** [comment]
It's basically #472

**Comment by expenses** [comment]
Ah, okay. I'll close this for now.

**Comment by tomaka** [comment]
I'd appreciate the network function alone though.

**Pull request closed without merging**
