### PR TITLE
Revisit story around unknown digest log items

### PR DESCRIPTION
**Pull request by tomaka**
Fix https://github.com/paritytech/smoldot/issues/2475

While Substrate supports Aura and Babe, other teams are free to extend Substrate to support other consensus algorithms (such as Nimbus). This PR revisits our strategy regarding these other consensus algorithms.

Before this PR, block headers that contain items that aren't supported by smoldot would simply fail to parse, with some whitelisted exceptions such as Polkadot parachains, Beefy, and Frontier. These exceptions were added for consensus algorithms that don't have any influence on whether a block is valid or not.

After this PR, we now successfully parse block headers even if they contain unrecognized consensus engines. However, the blocks verification code will fail if it is asked to verify a block header with an unrecognized consensus engine.

In order to understand this change, one must note that the parachain code of smoldot doesn't actually verify blocks. It simply follows the blocks that the relay chain considers as the best block for that parachain. If the relay chain says a block is valid, then the parachain code will consider that block as valid as well. It never actually verifies them itself.

This means that the change in this PR now enables parachains with unrecognized consensus engines.

Relay/standalone chains with unrecognized consensus engines, however, still aren't supported. After this PR, they will simply fail to verify blocks rather than fail to parse blocks.

A slightly related change that I've sneaked in this PR is how we handle chains that don't use any consensus engine.
Before this PR, chains that don't use any consensus engine are marked as `AllAuthorized` and will have see all incoming headers accepted. This can potentially lead to a DoS vector, as anyone can just create millions of fake blocks that are all considered as valid.
After this PR, chains that don't use any consensus engine are marked as `Unknown` and will now fail all block verifications. Again, this doesn't have any influence on parachains as the parachains code doesn't verify blocks anyway.

### CODE REVIEW

**Comment by tomaka** [comment]
Ok I'm a bit stupid. I've just realized that this breaks everything, since Beefy/Polkadot parachains are now considered as unknown consensus engines and thus blocks validation will fail.

**Comment by tomaka** [comment]
Fixed my previous comment by adding an `allow_unknown_consensus_engines` flag to the configuration of everything relevant.
It's set to `true` in the light client.

**Review by melekes — APPROVED** [review]

**Comment by sea212** [comment]
Awesome!

**Pull request merged**
