### PR TITLE
Inform users about the new repo

### PR DESCRIPTION
**Pull request by bkchr**
Closes: https://github.com/paritytech/smoldot/issues/3097

Is that okay @tomaka?

### CODE REVIEW

**Comment by tomaka** [comment]
Yeah, I had in mind to do a PR like that, just I was thinking of writing a bit more text, but also I don't know exactly what to write

**Comment by tomaka** [comment]
The CI failure can be fixed by putting a `0.7` here: https://github.com/paritytech/smoldot/blob/76994b52cd658a4ac1dc7a08f6bd4eba702e0e87/.github/workflows/ci.yml#L79

I don't know why it suddenly broke, but I had to do the same fix in the new repo.

**Comment by bkchr** [comment]
> Yeah, I had in mind to do a PR like that, just I was thinking of writing a bit more text, but also I don't know exactly what to write

Okay. I think I would move forward and if you have some better text/ideas just open a pr and we extend it! :)

**Comment by tomaka** [comment]
Also the CI fails because the spellcheck doesn't know the word "repo"

**Review by tomaka — APPROVED** [review]
My review doesn't count, but I guess I'll put it for the principle

**Comment by forgetso** [comment]
Why did the repo move to a new org?

**Comment by tomaka** [comment]
I'm no longer working at Parity and I'm continuing the development of smoldot through treasury proposals. Since the project doesn't "belong to Parity" "anymore" (the code in 2022 and before belongs to Parity, but everything is under GPL 3 regardless), it makes sense for it to be in a different organization.

The reason why we didn't simply move the repo is complicated and uninteresting.

**Comment by forgetso** [comment]
Thanks for the explanation @tomaka and good luck!

**Pull request merged**
