### PR TITLE
fix some clippy warnings

### PR DESCRIPTION
**Pull request by melekes**
Refs #1623 

Context: fixed some clippy warnings while reading the code.

### CODE REVIEW

**Review by tomaka — APPROVED** [review]
:+1: I've had in mind to enforce clippy check through CI, but obviously we need to fix all warnings first

**Comment by tomaka** [comment]
Feel free to merge your two PRs with the `automerge` label

**Comment by melekes** [comment]
@mergify rebase

**Comment by tomaka** [comment]
Mergify automatically updates branches

**Pull request merged**
