### PR TITLE
Move fields from GrandpaWarpSync into InProgressGrandpaWarpSync

### PR DESCRIPTION
**Pull request by expenses**
As discussed in DMs, this would make implementing the 'all' syncing behaviour easier. I'm not sure if we want to do this incrementally or go all-in with the idea that `Finished` should always return `Success` and we just try a different peer when something goes wrong.

### CODE REVIEW

**Comment by expenses** [comment]
I haven't touched `all.rs` yet

**Comment by tomaka** [comment]
I'd rather combine this with #555 somehow, to avoid the merge conflicts.

**Comment by expenses** [comment]
> I'd rather combine this with #555 somehow, to avoid the merge conflicts.

you mean https://github.com/paritytech/smoldot/pull/567 ? I can try merge it with that.

**Comment by tomaka** [comment]
#567 is only waiting for a review from you to be merged :grimacing:

**Comment by expenses** [comment]
Is this going to merge without a review? I'd rather do #567 first.

**Review by tomaka — APPROVED** [review]

**Comment by tomaka** [comment]
Next stop could be to add some utility methods on the `InProgress`, like `source_user_data_mut`, and simplify `all.rs` to use them.

**Pull request merged**
